title: Personal Page
author: Cynthia Gao
email: zg2323@columbia.edu
description: > # this means to ignore newlines until "baseurl:"
  A place to share my progress in learning math & computer science. 

# social links
twitter_username:  # DO NOT include the @ character, or else the build will fail!
github_username:  Cynzgao # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
